import { useRouter } from 'next/router'
import Footer from '../../components/Footer';
import Navbar from '../../components/Navbar'
import ProductDescription from '../../components/ProductDescription';
import { useEffect } from 'react';
import ProductNotFound from '../../components/ProductNotFound';
import Head from 'next/head';
import Ranking from '../../components/Ranking'

function Query({ query, id }) {
    const router = useRouter();

    return (
      <>
      <Head>
        {/* <title>RANKI - {product.entity}</title> */}
        <meta name="description" content="Generated by create next app" />
        <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logos/2.png" />
      </Head>
      {product == 'PRODUCT NOT AVAILABLE' ? 
        <>
        <Navbar />
      <ProductNotFound />
      <Footer />
      </>
      :
      <>
        <Navbar />
        <Ranking query={query} />
        <Footer />
        </>
      }
      </>
    )
}


export async function getServerSideProps(context) {
  const { q } = context.query;

  console.log("ID------>", q)
  // send a GET request with the id as a query parameter
  const response = await fetch(`https://grsvumxr5onti4rnxgin73azyq0fgqvy.lambda-url.us-east-2.on.aws/blackwidow/query?input=${q}`);
  const query = await response.json();
  console.log(product)
  return {
    props: {
      query
    },
  };
}

export default Query;